language: scala

matrix:
  include:
    # scala 2.10
    - jdk: oraclejdk8
      scala: 2.10.6
      env: SCALAZ_VERSION=7.2.8
    - jdk: oraclejdk8
      scala: 2.10.6
      env: SCALAZ_VERSION=7.1.11
    # scala 2.11
    - jdk: oraclejdk8
      scala: 2.11.8
      env: SCALAZ_VERSION=7.2.8
    - jdk: oraclejdk8
      scala: 2.11.8
      env: SCALAZ_VERSION=7.1.11
    # scala 2.12
    - jdk: oraclejdk8
      scala: 2.12.1
      env: SCALAZ_VERSION=7.2.8
    - jdk: oraclejdk8
      scala: 2.12.1
      env: SCALAZ_VERSION=7.1.11

branches:
  only:
  - master

before_script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi"

script:
  - sbt ++$TRAVIS_SCALA_VERSION test coverageReport
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

after_success:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
